[target.armv7-linux-androideabi]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--unresolved-symbols=ignore-in-object-files"
]

[target.aarch64-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--unresolved-symbols=ignore-in-object-files"
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1

[profile.dev]
panic = "abort"

[profile.bench]
panic = "abort"

[profile.test]
panic = "abort"
